config/projects/angry-omnibus-toolchain.rb, config/projects/omnibus-toolchain.rb, config/software/omnibus-toolchain.rb
This is to fix the failing build due to missing licensing data
=> [JEX-164] Add licensing data

config/projects/omnibus-toolchain.rb
This should fix licensing download errors on jenkins chef builders. On ruby 2.1.5 (the current ruby default version) the following code:
```
require 'open-uri'
open("https://www.openssl.org/source/license.html")
```
produces an error:
```
OpenSSL::SSL::SSLError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A
```
Ruby 2.1.8 is able to successfully download the license.
=> use ruby 2.1.8

files/mapfiles/solaris
This removes the mapfile which is no longer required in Solaris 10u11 and later.
Relates to COOL-502.
=> Only support Solaris 10u11 and newer

config/projects/omnibus-toolchain.rb
This Pull Request was opened by Chef Automate user Tom Duffield
This release of RubyGems fixes a number of bugs that will allow us to
unpin rainbow in chef and chefdk. Specifically,
https://github.com/sickill/rainbow/issues/44.
Signed-off-by: Tom Duffield <tom@chef.io>
Ready to merge? View this change in Chef Automate and click the Approve button: https://delivery.chef.co/e/chef/#/organizations/engineering-services/projects/omnibus-toolchain/changes/f5c439b9-c532-4b12-b4c8-754c109682b3
=> Update Rubygems to 2.6.10

.expeditor/config.yml
This was inadvertently missed in chef/omnibus-toolchain#74
=> Ensure update changelog respects `Expeditor: Skip All` label

.expeditor/config.yml
This will trigger uncached omnibus builds on the toolchain
projects when software or patches are updated in omnibus-software
@chef/engineering-services
=> Add expeditor subscription for omnibus-software merges

docs/Debian_Ubuntu_Linux.md
Going through this I found that Ruby 2.2 is at least required by the `omnibus` gem. I also had to use `FORCE_UNSAFE_CONFIGURE=1` otherwise `gtar` was really unhappy to run autoconf as root.
=> A few documentation fixes to bring this up-to-date.

config/software/msys2core.rb
Resolves https://github.com/chef/omnibus-toolchain/issues/94
=> Updating MSYS2 version, the exit 127 issue appears to be resolved now

config/projects/omnibus-toolchain.rb
This bump includes a *ton* of bugfixes and removes the need for 2 different patches to gtar (on macos/aix). This also fixes a CVE.
=> Use gtar 1.32

.expeditor/config.yml
The `#omnibus-rfr` channel no longer exists and the Releng team would
like to know status of various actions Expeditor is taking for this
repo. We'll also add a project alias which will make promotions easier.
=> Update Slack notification channels in Expeditor config

config/projects/omnibus-toolchain.rb
Tar 1.32 is not compatible with the Ubuntu 14.04's latest version of
dpkg-deb so pin it to 1.28, the last known working version.
=> Pin tar to 1.28 for Ubuntu 14.04

config/projects/omnibus-toolchain.rb, config/software/gtar.rb
In https://github.com/chef/omnibus-toolchain/pull/115 I accidentally said in the PR description that I was pinning tar to 1.28 but I actually pinned it to 1.29 because it was the oldest tar available in the latest omnibus-software. After doing a number of builds of a few of our omnibus projects I'm consistently seeing unexpected results. The Ubuntu 14.04 package sizes are consistently around 1 - 2 GB and testing those packages consistently fails. I believe that we need to pin tar back to 1.28 which we know was working so I copied omnibus-software's gtar software config file into this repo and added metadata for version 1.28.
=> Make Ubuntu 14.04 use tar 1.28

.expeditor/angry-release.omnibus.yml, .expeditor/release.omnibus.yml, Gemfile
Fix platform names in `angry-release.omnibus.yml` and `release.omnibus.yml` files to conform with what the new package publishing code in the omnibus gem expects and install the artifactory gem so it can be used by the package publishing code.
https://github.com/chef/omnibus-buildkite-plugin/issues/22
=> Fix platform names in [angry-]release.omnibus.yml files

.expeditor/angry-release.omnibus.yml, .expeditor/release.omnibus.yml, config/projects/omnibus-toolchain.rb
Added test support for `el-8-x86_64`.
As of March 31st 2019, SLES 11 is no longer generally supported. Per our
support process we will no longer officially support SLES 11.
As of April 30th 2019, Ubuntu 14.04 is no longer generally supported. Per our
support process we will no longer officially support Ubuntu 14.04.
As of October 31st 2018, FreeBSD 10 is no longer generally supported. Per our
support process we will no longer officially support FreeBSD 10.
See https://docs.chef.io/platforms.html#platform-end-of-life-policy
=> Update platform build/test matrix

.expeditor/angry-release.omnibus.yml, .expeditor/release.omnibus.yml
IBM is retiring support for RHEL 6 in Linux One cloud on Jan 17th 2020
where these systems are currently hosted,
so we are no longer able to support this platform in our build matrix.
Remove support for RHEL 6 s390x (zLinux)
IBM is retiring support for RHEL 6 in their hosted Linux One cloud on Jan 17th 2020,
so we are no longer able to support this platform in our build matrix.
=> Remove support for RHEL 6 s390x (zLinux)

.expeditor/angry-release-canary.omnibus.yml, .expeditor/angry-release.omnibus.yml, .expeditor/release-canary.omnibus.yml, .expeditor/release.omnibus.yml
This PR simply adds Debian 10 aarch64 support and has successful adhoc tests that can be found here:
https://buildkite.com/chef/chef-omnibus-toolchain-master-omnibus-adhoc/builds/223
https://buildkite.com/chef/chef-omnibus-toolchain-master-omnibus-angry-adhoc/builds/69
Signed-off-by: Christopher A. Snapp <csnapp@chef.io>
=> Add Debian 10 aarch64 to build/test map

.expeditor/angry-release.omnibus.yml, .expeditor/release.omnibus.yml
The gtar issue was resolved by using another AMI
Enable FreeBSD12
The gtar issue was resolved by msys by using another AMI
=> Enable FreeBSD12

config/software/gtar.rb
There's no need for this if we use 1.32 in https://github.com/chef/omnibus-toolchain/pull/147
=> Remove the old versions from the gtar def

.expeditor/angry-release-canary.omnibus.yml, .expeditor/angry-release.omnibus.yml, .expeditor/release-canary.omnibus.yml, .expeditor/release.omnibus.yml, config/projects/omnibus-toolchain.rb, resources/omnibus-toolchain/pkg/entitlements.plist
Updates to enable darwin/arm64 (M1) builds:
* Update openssl to 1.1.1i
* Update ruby to 2.7.2
Also: remove macOS 10.13 from the build matrices
=> Update openssl to 1.1.1j and ruby to 2.7.2 to enable m1 mac builds

omnibus-test.ps1, omnibus-test.sh
This logic has been moved into the Omnibus Buildkite Plugin.
These scripts can now be used outside of the Buildkite pipelines.
Signed-off-by: Tom Duffield <github@tomduffield.com>
=> Remove pipeline-specific logic from test scripts

config/projects/omnibus-toolchain.rb, omnibus-test.ps1
Pin expat to 2.1.0 for aix builds
Fix omnibus-test.ps1
Add dependency on ruby-cleanup. This removes a lot of unnecessary files, some of which were causing Apple notarization failures.
Remove bundler 1.x to satisfy ruby-cleanup.rb. We only need the bundler that comes with the ruby install.
Bump openssl to 1.1.k
=> Fix aix builds

config/software/helper-gems.rb
This is used by Server, Supermarket, Manage, and Backend for the build
time installation of gems. If we move it to toolchain then we can avoid
installing a ton of deps into our packages and also unblock supermarket
and manage which are totally broken trying to install Berkshelf right
now.
=> Add berkshelf to omnibus toolchain

.expeditor/angry-release-canary.omnibus.yml, .expeditor/angry-release.omnibus.yml, .expeditor/release-canary.omnibus.yml, .expeditor/release.omnibus.yml, kitchen.yml
We don't support Ubuntu 16.04 anymore
=> Stop building on EOL Ubuntu 16.04

config/software/omnibus-toolchain.rb
=> Remove workaround for Solaris 10 / FreeBSD 9

.expeditor/angry-release-canary.omnibus.yml, .expeditor/angry-release.omnibus.yml, .expeditor/release-canary.omnibus.yml, .expeditor/release.omnibus.yml
We don't support Debian 8 anywhere at this point.
=> Stop producing builds for Debian 8

config/software/gtar.rb, config/software/helper-gems.rb, config/software/omnibus-toolchain.rb
We only have 1.32 so this is pointless.
=> Remove gtar check for < 1.32

config/software/omnibus-toolchain.rb
nokogiri doesn't have a version set so it always dirties the omnibus cache. If we move it down the list of dependencies we can dirty less of the cache.
=> Build nokogiri later to optimize omnibus cache

.expeditor/config.yml, config/projects/omnibus-toolchain.rb, config/software/omnibus-toolchain.rb, omnibus-test.sh, package-scripts/angry-omnibus-toolchain/postinst, package-scripts/omnibus-toolchain/postinst
Move berkshelf build above nokogiri for omnibus cache optimization.
Pin berkshelf.
Symlink berks into BINDIR.
=> Only build berkshelf on specific platforms

config/projects/omnibus-toolchain.rb, omnibus-test.sh
FreeBSD was successfully building bash but it wasn't working correctly.
=> Test bash command substitution

config/projects/omnibus-toolchain.rb
Newer versions of ncurses cause build failures on Solaris
=> Pin ncurses to 5.9 on Solaris

.expeditor/adhoc-canary.omnibus.yml, .expeditor/angry-adhoc-canary.omnibus.yml, .expeditor/config.yml
macos 12 arm64 worker doesn't exist in canary org
canary org's macos 11 arm64 omnibus worker uses omnibus-toolchain
so it cannot be used to build omnibus-toolchain
=> Fix platforms in canary pipelines

.expeditor/adhoc-canary.omnibus.yml, .expeditor/angry-adhoc-canary.omnibus.yml, .expeditor/angry-release.omnibus.yml, .expeditor/release.omnibus.yml
Canonical extended support for Ubuntu 16.04 until 2026 so
we need to build Chef Infra on it.
https://github.com/chef/chef/pull/12086
=> Add ubuntu 1604 to build matrix

Gemfile
Build is failing with below error - 
```
An error occurred while installing ohai (17.7.8), and Bundler cannot continue.
Make sure that `gem install ohai -v '17.7.8' --source 'https://rubygems.org/'` succeeds before bundling.
In Gemfile:
omnibus-software was resolved to 4.0.0, which depends on
omnibus was resolved to 8.2.6, which depends on
ohai
```
Signed-off-by: jayashri garud <jgarud@msystechnologies.com>
https://buildkite.com/chef/chef-omnibus-toolchain-main-omnibus-angry-adhoc/builds/95#bc2de139-01f3-441f-a678-277b03d756b3
=> Pin ohai to 16.17.0

omnibus.rb
Our AIX systems in IBM cloud can't reliably handle the default number of workers.
=> Limit workers on AIX

Gemfile
A new version of omnibus-toolchain is deployed on all platforms. The new version includes ruby 2.7 so we no longer need to pin to an old version of ohai.
=> Unpin ohai in omnibus Gemfile

config/projects/omnibus-toolchain.rb
Pin xproto to 7.0.25. xproto 7.0.31 became the default version in omnibus-software but it failed to build on multiple non-x86_64 systems. (e.g. arm64, ppc64)
Pin curl to 7.80.0. curl 7.81.0 became the default version in omnibus-software but it failed to build on macos x86_64.
=> Fix regressions

.expeditor/adhoc-canary.omnibus.yml, .expeditor/angry-adhoc-canary.omnibus.yml, .expeditor/angry-release.omnibus.yml, .expeditor/release.omnibus.yml, config/projects/omnibus-toolchain.rb, config/software/cmake.rb, omnibus-test.ps1, omnibus-test.sh
Stop building on windows-2012r2-i386
We no longer need a 32 bit omnibus-toolchain package because the AMI used for windows-2012r2-i386 is the same used for the windows-2012r2-x86_64 platform.
Fix omnibus-test.ps1 and omnibus-test.sh
Unpin ncurses for solaris
Unpin curl
Unpin gtar
Update cmake
Bump berkshelf to 8.0.1
Add RHEL 9 to build matrices
=> IPACK-204 Prepare for new omnibus-toolchain build

.expeditor/adhoc-canary.omnibus.yml, .expeditor/angry-adhoc-canary.omnibus.yml, .expeditor/angry-release.omnibus.yml, .expeditor/release.omnibus.yml, config/projects/omnibus-toolchain.rb
Build ruby 3.1 and openssl 3
Use UCRT64 toolchain for 64 bit Windows builds
=> IPACK-204 use ruby 3.1, openssl 3 and UCRT64

.expeditor/config.yml
Until we get enough ppc64 and ppc64le systems to build both
omnibus-toolchain and angry-omnibus-toolchain at the same time.
=> Disable auto trigger of omnibus/release pipeline

.expeditor/config.yml, .expeditor/verify.pipeline.yml, config/projects/angry-omnibus-toolchain.rb, config/projects/omnibus-toolchain.rb, config/software/omnibus-toolchain.rb
This PR adds a verify pipeline that lints ruby files on pull-request commits
BS-83 (JIRA)
=> Lint ruby files using chefstyle on pull-requests

config/projects/omnibus-toolchain.rb
Signed-off-by: poorndm <poorndm@progress.com>
Build failed  for  omnibus-toolchain  on Freebsd,AIX and Solaris platforms
Build Log : https://buildkite.com/chef/chef-omnibus-toolchain-main-omnibus-angry-adhoc/builds/8
FreeBsd Error : bash compilation error -  shells/bash: static option fails to link with duplicate symbol
<head>
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:////Users/poorndm/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip.htm">
<link rel=File-List
href="file:////Users/poorndm/Library/Group%20Containers/UBF8T346G9.Office/TemporaryItems/msohtmlclip/clip_filelist.xml">
<style>
</style>
</head>
<meta charset=utf-8>
<body link="#0563C1" vlink="#954F72">
<meta …
=> Fix build issues on Free bsd , solaris and AIX #1744

config/projects/omnibus-toolchain.rb
Curl Build failed on solaris with nghttp2 unreferenced symbols.
This issue occurs for the curl version > 7.81.0
Pinned curl version to 7.81.0  for solrais
Error :
nghttp2_pack_settings_payload       ../lib/.libs/libcurl.so
  | nghttp2_session_send                ../lib/.libs/libcurl.so
  | ld: fatal: symbol referencing errors
  | collect2: error: ld returned 1 exit status
  | gmake[2]: *** [Makefile:991: curl] Error 1
=> Fix Solaris Build Issue

.expeditor/adhoc-canary.omnibus.yml, .expeditor/angry-adhoc-canary.omnibus.yml, .expeditor/angry-release.omnibus.yml, .expeditor/config.yml, .expeditor/release.omnibus.yml, Gemfile.lock, config/software/gtar.rb
this will remove mac 10.15 from pipelines as this is outdated and making  mac 11 as builder and also freebsd 12 removal and making 13 as builder
And also will pick the latest OMNIBUS_BUILDKITE_PLUGIN_VERSION where new IBM hosts are pushed
=> remove mac10.15 from pipeline and make mac 11 as builder

.expeditor/adhoc-canary.omnibus.yml, .expeditor/angry-adhoc-canary.omnibus.yml, .expeditor/angry-release.omnibus.yml, .expeditor/config.yml, .expeditor/release.omnibus.yml, config/projects/omnibus-toolchain.rb
Picking the latest digi cert token for windows platforms and also removal of el-6 from release pipeline since its EOL
=> remove el6 and update buildkite-plugin version

.expeditor/adhoc-canary.omnibus.yml, .expeditor/angry-adhoc-canary.omnibus.yml, .expeditor/angry-release.omnibus.yml, .expeditor/config.yml, .expeditor/release.omnibus.yml, Gemfile.lock, config/software/omnibus-toolchain.rb
1. Removal of mac 11 from pipeline as its EOL and updating 12 as builder.
2. Picked latest sha from omnibus-buildkite-plugin to get those changes.
3. Updated latest version of omnibus-software and sha.
4. Stop building berkshelf for mac as its not required for mac platforms.
=> remove mac 11 as its EOL and update 12 as builder omniubs toolchain/muthuja

Gemfile.lock
this change is fix for the below errors 
> Running `bundle install` with bundler 2.3.26
--
  | Bundler::ProductionError: Your bundle only supports platforms ["aarch64-linux", "arm64-darwin-20", "powerpc-aix-7", "powerpc64-linux", "powerpc64le-linux", "s390x-linux", "sparc-solaris-2.11", "x86_64-darwin-19", "x86_64-freebsd-12", "x86_64-linux", "x86_64-solaris-2.11"] but your local platform is x86_64-freebsd-13. Add the current platform to the lockfile with
  | `bundle lock --add-platform x86_64-freebsd-13` and try again.
=> adding darwin-20 and freebsd-13 x86_64 to the platform list
