chef/omnibus-toolchain

config/projects/omnibus-toolchain.rb
config/software/omnibus-toolchain.rb
package-scripts/angry-omnibus-toolchain/postinst
package-scripts/omnibus-toolchain/postinst

Resolves https://github.com/chef/omnibus-toolchain/issues/31 and adds gtar

Add gtar, setup postinst scripts correctly

---

config/projects/omnibus-toolchain.rb
config/software/omnibus-toolchain.rb

Remove fakeroot, update some versions

---

package-scripts/angry-omnibus-toolchain/postinst
package-scripts/omnibus-toolchain/postinst

Update symlinks correctly

---

package-scripts/angry-omnibus-toolchain/postrm
package-scripts/omnibus-toolchain/postrm

This Pull Request was opened by Chef Automate user Jaymala Sinha
Ready to merge? View this change in Chef Automate and click the Approve button: https://delivery.chef.co/e/chef/#/organizations/engineering-services/projects/omnibus-toolchain/changes/538f47da-84c7-4a64-93f0-969adb65a44b

[BEN-157] Remove installed symlinks

---

Gemfile
config/projects/omnibus-toolchain.rb

This Pull Request was opened by Chef Automate user Scott Hain
Ready to merge? View this change in Chef Automate and click the Approve button: https://delivery.chef.co/e/chef/#/organizations/engineering-services/projects/omnibus-toolchain/changes/332e996e-492e-4b08-b11a-6a90069ddedf

Ping openssl on aix for the curl bug, get off the crazy branches

---

package-scripts/angry-omnibus-toolchain/postrm
package-scripts/omnibus-toolchain/postrm

This Pull Request was opened by Chef Automate user Jaymala Sinha
Ready to merge? View this change in Chef Automate and click the Approve button: https://delivery.chef.co/e/chef/#/organizations/engineering-services/projects/omnibus-toolchain/changes/85e37c6c-a17c-48d1-ba80-3299dec084d3

postrm should remove the install directory

---

config/projects/omnibus-toolchain.rb

This Pull Request was opened by Chef Automate user Scott Hain
Ready to merge? View this change in Chef Automate and click the Approve button: https://delivery.chef.co/e/chef/#/organizations/engineering-services/projects/omnibus-toolchain/changes/04620acd-274f-4065-9314-ed0dfb4e9f92

Pin solaris openssl version, as the latest is breaking on solaris 10

---

config/projects/omnibus-toolchain.rb

This Pull Request was opened by Chef Automate user Scott Hain
Ready to merge? View this change in Chef Automate and click the Approve button: https://delivery.chef.co/e/chef/#/organizations/engineering-services/projects/omnibus-toolchain/changes/f503679d-c6c2-454b-868f-b3353a2ca20d

Pin solaris 10 a bit farther back

---

config/projects/omnibus-toolchain.rb

This Pull Request was opened by Chef Automate user Scott Hain
Ready to merge? View this change in Chef Automate and click the Approve button: https://delivery.chef.co/e/chef/#/organizations/engineering-services/projects/omnibus-toolchain/changes/b17ed6e2-ab6a-4a65-a5e3-1046c3451dbb

Pin bundler to 1.13.6

---

Gemfile

Signed-off-by: Matt Ray <matthewhray@gmail.com>

Restore to pedump to upstream dependency, per @ksubrama's recommendation

---

config/software/msys2core.rb

Add auto{make,conf,gen} & libtool to windows base

---

config/projects/omnibus-toolchain.rb

@tduffield @schisamo Another PR queued up for your testing pleasure.

Add version string

---

.expeditor/config.yml

Full details on this new feature can be found at:
https://github.com/chef/es-lita/pull/67

Begin using Expeditor's merge_actions

---

config/projects/omnibus-toolchain.rb

omnibus-toolchain and chef are both special as there is an `angry-*`
project that shadows the main project.

Use proper VERSION file loading logic

---

config/projects/angry-omnibus-toolchain.rb

Ensure current_file is declared in angry-omnibus-toolchain

---

config/projects/omnibus-toolchain.rb

Update MSI signing identity

---

package-scripts/angry-omnibus-toolchain/postrm
package-scripts/omnibus-toolchain/postrm

If the package manager already supports clean upgrades, that is!

Update pkgrm scripts to not nuke directory

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md
config/projects/omnibus-toolchain.rb

Update versions to be more current and deal with git CVE

---

.expeditor/config.yml

Signed-off-by: Tom Duffield <tom@chef.io>

Update Expeditor config to 0.5.0 syntax

---

config/projects/omnibus-toolchain.rb

Upgrade ruby 2.4.2 and remove rubygems version pin

---

docs/RHEL_CentOS_Fedora.md

Update RHEL docs

---

config/projects/omnibus-toolchain.rb

Pin curl and rubygems

---

config/software/msys2core.rb

https://github.com/Alexpux/MSYS2-pacman/issues/48

Don't update pacman

---

Gemfile
config/projects/omnibus-toolchain.rb
scripts/verify.sh

@chef/engineering-services 
The verification script we can enable once we get new-ci stable.

Unpin git version, add verification script, update gems

---

resources/omnibus-toolchain/ips/angry-omnibus-toolchain-symlinks.erb

Create symlinks for angry-omnibus-toolchain IPS package

---

.expeditor/config.yml
.github/CODEOWNERS

Send all notifications to the BEN team

---

.expeditor/config.yml

Update notification room

---

ci/verify.sh

Add a verification script so we don't have install-time failures

---

config/projects/omnibus-toolchain.rb

Make sure https://github.com/chef/omnibus-software/pull/939 is merged beforehand!

update berkshelf, ruby, and other versions

---

ci/verify.sh

Fix tests up

---

ci/verify.sh

Fix tests some more

---

.kitchen.yml

Update build record

---

config/software/cmake.rb
config/software/omnibus-toolchain.rb

Merge https://github.com/chef/omnibus-software/pull/979
before merging this PR.

Add windows cmake to toolchain

---

ci/verify.sh

ssh git clone fails on AIX tester

Swap git:// clone to https:// for verify

---

docs/aix_toolchain_base
docs/solaris_toolchain_base.md

Docs edit will trigger the release

Update toolchain version to include latest bundler gem

---

config/projects/omnibus-toolchain.rb

This version fixes multiple bugs and several CVEs.

Update to Ruby 2.5.3

---

README.md

Build on Solaris 11.2 for SPARC

---

config/projects/omnibus-toolchain.rb

Resolves multiple CVEs in rubygems

Update ruby to 2.5.5

---

config/projects/omnibus-toolchain.rb

Update ruby and berkshelf versions

---

.expeditor/config.yml
.github/CODEOWNERS
.github/ISSUE_TEMPLATE/BUG_TEMPLATE.md
.github/ISSUE_TEMPLATE/DESIGN_PROPOSAL.md
.github/ISSUE_TEMPLATE/ENHANCEMENT_REQUEST_TEMPLATE.md
.github/ISSUE_TEMPLATE/SUPPORT_QUESTION.md
.github/lock.yml
CODE_OF_CONDUCT.md
CONTRIBUTING.md
README.md

Fix the expeditor labels
Add various github templates
Add project information to the readme
Update the codeowners in github
Add the lockbot to lock old issues
Add a code of conduct file
Add a contributing file

Update this repo to comply with our OSS guidelines

---

config/templates/helper-sh/install-omnibus-product.erb

Use full path when calling mixlib-install in `install-omnibus-product`.

Use full path when calling mixlib-install

---

config/templates/helper-sh/install-omnibus-product.erb

Use `product_name` variable instead of just `product`.

Use product_name variable instead of just product

---

config/templates/helper-exe/install-omnibus-product.ps1.erb
config/templates/helper-sh/install-omnibus-product.erb

Define `Get-Win32OS` function in `install-omnibus-product.ps1`.
Add small output to install-omnibus-product.

Fix install-omnibus-product.ps1

---

config/software/helper-sh.rb
config/templates/helper-sh/load-omnibus-toolchain.erb

Add AIX specific paths to load-omnibus-toolchain

---

.expeditor/angry-release.omnibus.yml
.expeditor/config.yml
.expeditor/release.omnibus.yml
omnibus-test.ps1
omnibus-test.sh

Create omnibus buildkite pipelines

---

config/templates/helper-sh/install-omnibus-product.erb
omnibus-test.ps1
omnibus-test.sh

Fix omnibus-test.* scripts.
Specify product name when installing omnibus product using `install-omnibus-product` script. This is necessary especially for Solaris' install procedure.

Fixes for omnibus buildkite pipeline

---

.expeditor/config.yml

Change subscription to omnibus-software to trigger correct pipeline

---

.expeditor/angry-release.omnibus.yml
.expeditor/release.omnibus.yml
config/projects/omnibus-toolchain.rb

Update Software Cert for macOS signing & add Debian 10 testers

---

MAINTAINERS.md

Signed-off-by: Scott Hain <elejia@gmail.com>
Added @jaymalasinha as maintainer - feel free to change as appropriate!

Remove myself as maintainer

---

.expeditor/angry-release.omnibus.yml
.expeditor/release.omnibus.yml
config/projects/omnibus-toolchain.rb
config/software/msys2core.rb
config/software/omnibus-toolchain.rb
omnibus-test.ps1
omnibus-test.sh

Install unix/linux tools required to build chef-workstation

---

.expeditor/angry-release-canary.omnibus.yml
.expeditor/config.yml
.expeditor/release-canary.omnibus.yml
.expeditor/release.omnibus.yml
omnibus-test.ps1
omnibus-test.sh

Add platforms and omnibus-test improvements

---

.expeditor/config.yml

Expeditor config update to bump major release version

Remove Windows msys2 from toolchain

---

.expeditor/config.yml

Fix expeditor config

---

package-scripts/angry-omnibus-toolchain/postinst
package-scripts/omnibus-toolchain/postinst
resources/omnibus-toolchain/ips/angry-omnibus-toolchain-symlinks.erb
resources/omnibus-toolchain/ips/omnibus-toolchain-symlinks.erb

Remove stale links for fakeroot and berks
Remove stale links for fakeroot and berks

Remove stale symlinks

---

.expeditor/angry-release.omnibus.yml
.expeditor/release-canary.omnibus.yml
.expeditor/release.omnibus.yml

Enable macos-11.0 tester for omnibus-toolchain

---

.expeditor/angry-release.omnibus.yml
.expeditor/release.omnibus.yml

Enable support for Zlinux(s390x) RHEL8 and SLES15
Enable support for Zlinux(s390x) RHEL8 and SLES15

Enable support for Zlinux(s390x) RHEL8 and SLES15

---

.expeditor/angry-release.omnibus.yml
.expeditor/release.omnibus.yml

Post ad-hoc build #225 in omnibus-toolchain, the gtar and tar binary tests
fail with the following error
-su-5.0$ which gtar
/opt/omnibus-toolchain/bin/gtar
-su-5.0$ gtar --version
tar (GNU tar) 1.32
ld-elf.so.1: /opt/omnibus-toolchain/bin/gtar: Undefined symbol "fputs_unlocked@FBSD_1.6"
-su-5.0$ ls -l /opt/omnibus-toolchain/bin/gtar
lrwxr-xr-x  1 root  wheel  39 Sep 10 13:47 /opt/omnibus-toolchain/bin/gtar -> /opt/omnibus-toolchain/embedded/bin/tar
-su-5.0$ /opt/omnibus-toolchain/embedded/bin/tar --version
tar (GNU tar) 1.32
ld-elf.so.1: /opt/omnibus-toolchain/embedded/bin/tar: Undefined symbol "fputs_unlocked@FBSD_1.6"

Disable freebsd-12 until gtar and tar commands are fixed

---

config/projects/omnibus-toolchain.rb

There's no need to check this anymore.

Remove support for Ubuntu 14.04

---

Gemfile

Signed-off-by: jayashri garud <jgarud@msystechnologies.com>
Added environment variables to load `omnibus` and `omnibus-software` gem dynamically from different repositories and branches
- [ X] Chore (non-breaking change that does not add functionality or fix an issue)
- [ X] I have read the **CONTRIBUTING** document.
- [X ] All commits have been signed-off for [the Developer Certificate of Origin](https://github.com/chef/chef/blob/master/CONTRIBUTING.md#developer-certification-of-origin-dco).

updating Gemfile to support environment variables

---

config/projects/omnibus-toolchain.rb

Pin git for solaris

---

omnibus-test.sh

Add "berks --version" to omnibus-test.sh

---

README.md

Minor updates to align with the true state

Update some platform information in the readme

---

.github/lock.yml

Remove the GitHub lockfile config

---

omnibus-test.sh

Fix path to berks in omnibus-test.sh

---

config/software/omnibus-toolchain.rb

Remove rubygems and bundler dependencies

---

config/projects/omnibus-toolchain.rb

This includes a large number of bug fixes and CVE fixes

Update Ruby from 2.7.2 to 2.7.4

---

.expeditor/angry-release-canary.omnibus.yml
.expeditor/angry-release.omnibus.yml
.expeditor/release-canary.omnibus.yml
.expeditor/release.omnibus.yml

Test freebsd packages on freebsd 13

---

.expeditor/angry-release-canary.omnibus.yml
.expeditor/angry-release.omnibus.yml
.expeditor/release-canary.omnibus.yml
.expeditor/release.omnibus.yml

Update platforms in pipelines

---

config/projects/omnibus-toolchain.rb

Signed-off-by: Michael Maslanka <maslanka@progress.com>

Remove expat pin

---

Gemfile

'main' branch replaced the 'master' branch

---

.expeditor/adhoc-canary.omnibus.yml
.expeditor/angry-adhoc-canary.omnibus.yml
.expeditor/angry-release.omnibus.yml
.expeditor/release.omnibus.yml

Replace ubuntu 1604 aarch64 with x86_64

---

.expeditor/release.omnibus.yml

Produce macOS 12 x86_64 packages

---

.expeditor/adhoc-canary.omnibus.yml
.expeditor/angry-adhoc-canary.omnibus.yml
.expeditor/angry-release.omnibus.yml
.expeditor/release.omnibus.yml

Produce Windows 11 and 2022 packages

---

config/projects/omnibus-toolchain.rb

This resolves a number of bugs and 3 CVEs

Update Ruby from 2.7.4 to 2.7.5

---

.expeditor/adhoc-canary.omnibus.yml
.expeditor/angry-adhoc-canary.omnibus.yml
.expeditor/angry-release.omnibus.yml
.expeditor/release.omnibus.yml

Update macos versions in omnibus pipeline shim files

---

.expeditor/config.yml

Subscribe to the project_promoted workload

---

config/projects/omnibus-toolchain.rb

Pin openssl to 1.1.1m .
Signed-off-by: jayashri garud <jgarud@msystechnologies.com>

Pin openssl to 1.1.1m

---

config/projects/omnibus-toolchain.rb

Pin libtool for aix

---

config/projects/omnibus-toolchain.rb

Signed-off-by: Poornima <poorndm@progress.com>

Update signing Identity 

---

.expeditor/config.yml
omnibus.rb

Signed-off-by: Evan Ahlberg <evanahlberg@gmail.com>
Updates the omnibus configuration so omnibus release and omnibus ad-hoc builds using internal sources (artifactory).
BS-117 (Jira)

update omnibus to use internal sources

---

omnibus.rb

Signed-off-by: poorndm <poorndm@progress.com>
Omnibus-toolchain build started failing on all platforms with  below error, post PR  https://github.com/chef/omnibus-toolchain/pull/219 merge.
```
Error 
bundler: failed to load command: omnibus (/var/lib/buildkite-agent/builds/omnibus-amazon-2022-aarch64-chef-i-0cc6ff1d478aa6884-1/chef/chef-omnibus-toolchain-main-omnibus-adhoc/vendor/bundle/ruby/3.1.0/bin/omnibus) 
```
Reverted the changes made to omnibus.rb until the issue is fixed by rel-eng team.

Fix build issue - Reverting the changes made PR - 219

---

.expeditor/release.omnibus.yml

Add rocky linux-8

---

.expeditor/adhoc-canary.omnibus.yml
.expeditor/angry-adhoc-canary.omnibus.yml
.expeditor/release.omnibus.yml

renaming these match the queue name:

renaming omnibus queue

---

.expeditor/adhoc-canary.omnibus.yml
.expeditor/angry-adhoc-canary.omnibus.yml
.expeditor/angry-release.omnibus.yml
.expeditor/release.omnibus.yml

Removed support for el-6-i686 due to compatibility issues

---

.expeditor/config.yml

Enable auto trigger of omnibus/release pipeline - Revert PR 213 changes

---

Gemfile.lock
docs/Gemfile_Lock.md

adding an additional platform.

adding two more platforms

---

.expeditor/angry-release.omnibus.yml
.expeditor/config.yml
config/projects/omnibus-toolchain.rb

Add Rocky-8 support - Angry omnibus-toolchain

---

.expeditor/adhoc-canary.omnibus.yml
.expeditor/angry-adhoc-canary.omnibus.yml
.expeditor/angry-release.omnibus.yml
.expeditor/release.omnibus.yml

Adding rockylinux9 to omnibus-toolchain

---

.expeditor/adhoc-canary.omnibus.yml
.expeditor/angry-adhoc-canary.omnibus.yml
.expeditor/angry-release.omnibus.yml
.expeditor/release.omnibus.yml

Adding rocky9 arm64 to omnibus-toolchain

---

config/projects/omnibus-toolchain.rb

Unpin curl on solaris

---

config/projects/omnibus-toolchain.rb

Unpin libxslt and libxml on windows

---

Gemfile.lock

Update to latest omnibus-software version

---

config/projects/omnibus-toolchain.rb

Downgrade bash to fix solaris issue

---

.expeditor/adhoc-canary.omnibus.yml
.expeditor/angry-adhoc-canary.omnibus.yml
.expeditor/angry-release.omnibus.yml
.expeditor/release.omnibus.yml

this changes will add new amazon 2023 builder and tester to omnibus toolchain and angry omnibus-toolchain

Support amazon2023 

---

.expeditor/config.yml

commenting buildkite plugin version so that it will pick directly from expedtior

comment the omnibus-buildkite plugin version so that it will pick it automatically from expeditor

---

.expeditor/adhoc-canary.omnibus.yml
.expeditor/angry-adhoc-canary.omnibus.yml
.expeditor/angry-release.omnibus.yml
.expeditor/config.yml
.expeditor/release.omnibus.yml

This PR modifies the pipeline configuration to include support for macOS 13 and 14 ARM architectures

Add support for Macos - 13 and 14

---

Gemfile.lock

Signed-off-by: Phil Dibowitz <phil@ipom.com>

Bump bundler version

---

.expeditor/adhoc-canary.omnibus.yml
.expeditor/angry-adhoc-canary.omnibus.yml
.expeditor/angry-release.omnibus.yml
.expeditor/release.omnibus.yml

This pull request adds support for Ubuntu 24.04  to the Omnibus-Toolchain project.

Add Support Ubuntu 24.04

---

Gemfile
Gemfile.lock

Brings in fixes for the windows builders.

Sean sype progress/chef 21530 platform support windows2025 omnibus
